platform: linux

image_resource:
  type: docker-image
  source:
    repository: 127.0.0.1:5000/java
    tag: "8"
    insecure_registries: ["127.0.0.1:5000"]
inputs:
- name: source-code

outputs:
- name: target-web

run:
  path: source-code/concourse/tasks/package-web.sh
